title: BabyAGI
email: 
description: >-
  BabyAGI is an AI-powered task management system that uses OpenAI and Pinecone APIs to create, prioritize, and execute tasks.
baseurl: ""
url: "https://babyagi.org"
logo: docs/babyagi.png
twitter_username: babyagi_
github_username:  yoheinakajima
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
include: [docs]
plugins:
- jekyll-remote-theme
